// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rnehpkppkmgpngwlwdii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuZWhwa3Bwa21ncG5nd2x3ZGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NTY2NDIsImV4cCI6MjA3NTIzMjY0Mn0.m9p4A5GwpAfiyehgjUcmweU1docdHTz9zMD_0G1Ndqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);